//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NorthwindModel", "Products_FK01", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JayDataExamples.NorthwindDB.Category), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Product), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Orders_FK00", "Customers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JayDataExamples.NorthwindDB.Customer), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Order), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Orders_FK02", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JayDataExamples.NorthwindDB.Employee), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Order), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Order_Details_FK00", "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JayDataExamples.NorthwindDB.Product), "Order_Details", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Order_Detail), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Order_Details_FK01", "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JayDataExamples.NorthwindDB.Order), "Order_Details", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Order_Detail), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Orders_FK01", "Shippers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JayDataExamples.NorthwindDB.Shipper), "Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Order), true)]
[assembly: EdmRelationshipAttribute("NorthwindModel", "Products_FK00", "Suppliers", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(JayDataExamples.NorthwindDB.Supplier), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JayDataExamples.NorthwindDB.Product), true)]

#endregion

namespace JayDataExamples.NorthwindDB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NorthwindEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
        /// </summary>
        public NorthwindEntities() : base("name=NorthwindEntities", "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        public NorthwindEntities(string connectionString) : base(connectionString, "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NorthwindEntities object.
        /// </summary>
        public NorthwindEntities(EntityConnection connection) : base(connection, "NorthwindEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order_Detail> Order_Details
        {
            get
            {
                if ((_Order_Details == null))
                {
                    _Order_Details = base.CreateObjectSet<Order_Detail>("Order_Details");
                }
                return _Order_Details;
            }
        }
        private ObjectSet<Order_Detail> _Order_Details;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shipper> Shippers
        {
            get
            {
                if ((_Shippers == null))
                {
                    _Shippers = base.CreateObjectSet<Shipper>("Shippers");
                }
                return _Shippers;
            }
        }
        private ObjectSet<Shipper> _Shippers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Supplier> Suppliers
        {
            get
            {
                if ((_Suppliers == null))
                {
                    _Suppliers = base.CreateObjectSet<Supplier>("Suppliers");
                }
                return _Suppliers;
            }
        }
        private ObjectSet<Supplier> _Suppliers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Order_Details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrder_Details(Order_Detail order_Detail)
        {
            base.AddObject("Order_Details", order_Detail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shippers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShippers(Shipper shipper)
        {
            base.AddObject("Shippers", shipper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Suppliers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSuppliers(Supplier supplier)
        {
            base.AddObject("Suppliers", supplier);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="category_ID">Initial value of the Category_ID property.</param>
        /// <param name="category_Name">Initial value of the Category_Name property.</param>
        public static Category CreateCategory(global::System.Int32 category_ID, global::System.String category_Name)
        {
            Category category = new Category();
            category.Category_ID = category_ID;
            category.Category_Name = category_Name;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Category_ID
        {
            get
            {
                return _Category_ID;
            }
            set
            {
                if (_Category_ID != value)
                {
                    OnCategory_IDChanging(value);
                    ReportPropertyChanging("Category_ID");
                    _Category_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Category_ID");
                    OnCategory_IDChanged();
                }
            }
        }
        private global::System.Int32 _Category_ID;
        partial void OnCategory_IDChanging(global::System.Int32 value);
        partial void OnCategory_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category_Name
        {
            get
            {
                return _Category_Name;
            }
            set
            {
                OnCategory_NameChanging(value);
                ReportPropertyChanging("Category_Name");
                _Category_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category_Name");
                OnCategory_NameChanged();
            }
        }
        private global::System.String _Category_Name;
        partial void OnCategory_NameChanging(global::System.String value);
        partial void OnCategory_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Picture
        {
            get
            {
                return StructuralObject.GetValidValue(_Picture);
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.Byte[] _Picture;
        partial void OnPictureChanging(global::System.Byte[] value);
        partial void OnPictureChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK01", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("NorthwindModel.Products_FK01", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("NorthwindModel.Products_FK01", "Products", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customer_ID">Initial value of the Customer_ID property.</param>
        /// <param name="company_Name">Initial value of the Company_Name property.</param>
        public static Customer CreateCustomer(global::System.String customer_ID, global::System.String company_Name)
        {
            Customer customer = new Customer();
            customer.Customer_ID = customer_ID;
            customer.Company_Name = company_Name;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer_ID
        {
            get
            {
                return _Customer_ID;
            }
            set
            {
                if (_Customer_ID != value)
                {
                    OnCustomer_IDChanging(value);
                    ReportPropertyChanging("Customer_ID");
                    _Customer_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Customer_ID");
                    OnCustomer_IDChanged();
                }
            }
        }
        private global::System.String _Customer_ID;
        partial void OnCustomer_IDChanging(global::System.String value);
        partial void OnCustomer_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company_Name
        {
            get
            {
                return _Company_Name;
            }
            set
            {
                OnCompany_NameChanging(value);
                ReportPropertyChanging("Company_Name");
                _Company_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company_Name");
                OnCompany_NameChanged();
            }
        }
        private global::System.String _Company_Name;
        partial void OnCompany_NameChanging(global::System.String value);
        partial void OnCompany_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact_Name
        {
            get
            {
                return _Contact_Name;
            }
            set
            {
                OnContact_NameChanging(value);
                ReportPropertyChanging("Contact_Name");
                _Contact_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact_Name");
                OnContact_NameChanged();
            }
        }
        private global::System.String _Contact_Name;
        partial void OnContact_NameChanging(global::System.String value);
        partial void OnContact_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact_Title
        {
            get
            {
                return _Contact_Title;
            }
            set
            {
                OnContact_TitleChanging(value);
                ReportPropertyChanging("Contact_Title");
                _Contact_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact_Title");
                OnContact_TitleChanged();
            }
        }
        private global::System.String _Contact_Title;
        partial void OnContact_TitleChanging(global::System.String value);
        partial void OnContact_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postal_Code
        {
            get
            {
                return _Postal_Code;
            }
            set
            {
                OnPostal_CodeChanging(value);
                ReportPropertyChanging("Postal_Code");
                _Postal_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Postal_Code");
                OnPostal_CodeChanged();
            }
        }
        private global::System.String _Postal_Code;
        partial void OnPostal_CodeChanging(global::System.String value);
        partial void OnPostal_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK00", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("NorthwindModel.Orders_FK00", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("NorthwindModel.Orders_FK00", "Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employee_ID">Initial value of the Employee_ID property.</param>
        /// <param name="last_Name">Initial value of the Last_Name property.</param>
        /// <param name="first_Name">Initial value of the First_Name property.</param>
        public static Employee CreateEmployee(global::System.Int32 employee_ID, global::System.String last_Name, global::System.String first_Name)
        {
            Employee employee = new Employee();
            employee.Employee_ID = employee_ID;
            employee.Last_Name = last_Name;
            employee.First_Name = first_Name;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Employee_ID
        {
            get
            {
                return _Employee_ID;
            }
            set
            {
                if (_Employee_ID != value)
                {
                    OnEmployee_IDChanging(value);
                    ReportPropertyChanging("Employee_ID");
                    _Employee_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Employee_ID");
                    OnEmployee_IDChanged();
                }
            }
        }
        private global::System.Int32 _Employee_ID;
        partial void OnEmployee_IDChanging(global::System.Int32 value);
        partial void OnEmployee_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birth_Date
        {
            get
            {
                return _Birth_Date;
            }
            set
            {
                OnBirth_DateChanging(value);
                ReportPropertyChanging("Birth_Date");
                _Birth_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birth_Date");
                OnBirth_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birth_Date;
        partial void OnBirth_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirth_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Hire_Date
        {
            get
            {
                return _Hire_Date;
            }
            set
            {
                OnHire_DateChanging(value);
                ReportPropertyChanging("Hire_Date");
                _Hire_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hire_Date");
                OnHire_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Hire_Date;
        partial void OnHire_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnHire_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postal_Code
        {
            get
            {
                return _Postal_Code;
            }
            set
            {
                OnPostal_CodeChanging(value);
                ReportPropertyChanging("Postal_Code");
                _Postal_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Postal_Code");
                OnPostal_CodeChanged();
            }
        }
        private global::System.String _Postal_Code;
        partial void OnPostal_CodeChanging(global::System.String value);
        partial void OnPostal_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Home_Phone
        {
            get
            {
                return _Home_Phone;
            }
            set
            {
                OnHome_PhoneChanging(value);
                ReportPropertyChanging("Home_Phone");
                _Home_Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Home_Phone");
                OnHome_PhoneChanged();
            }
        }
        private global::System.String _Home_Phone;
        partial void OnHome_PhoneChanging(global::System.String value);
        partial void OnHome_PhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                OnExtensionChanging(value);
                ReportPropertyChanging("Extension");
                _Extension = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extension");
                OnExtensionChanged();
            }
        }
        private global::System.String _Extension;
        partial void OnExtensionChanging(global::System.String value);
        partial void OnExtensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Reports_To
        {
            get
            {
                return _Reports_To;
            }
            set
            {
                OnReports_ToChanging(value);
                ReportPropertyChanging("Reports_To");
                _Reports_To = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reports_To");
                OnReports_ToChanged();
            }
        }
        private Nullable<global::System.Int32> _Reports_To;
        partial void OnReports_ToChanging(Nullable<global::System.Int32> value);
        partial void OnReports_ToChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK02", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("NorthwindModel.Orders_FK02", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("NorthwindModel.Orders_FK02", "Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="order_ID">Initial value of the Order_ID property.</param>
        /// <param name="customer_ID">Initial value of the Customer_ID property.</param>
        public static Order CreateOrder(global::System.Int32 order_ID, global::System.String customer_ID)
        {
            Order order = new Order();
            order.Order_ID = order_ID;
            order.Customer_ID = customer_ID;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order_ID
        {
            get
            {
                return _Order_ID;
            }
            set
            {
                if (_Order_ID != value)
                {
                    OnOrder_IDChanging(value);
                    ReportPropertyChanging("Order_ID");
                    _Order_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Order_ID");
                    OnOrder_IDChanged();
                }
            }
        }
        private global::System.Int32 _Order_ID;
        partial void OnOrder_IDChanging(global::System.Int32 value);
        partial void OnOrder_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer_ID
        {
            get
            {
                return _Customer_ID;
            }
            set
            {
                OnCustomer_IDChanging(value);
                ReportPropertyChanging("Customer_ID");
                _Customer_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Customer_ID");
                OnCustomer_IDChanged();
            }
        }
        private global::System.String _Customer_ID;
        partial void OnCustomer_IDChanging(global::System.String value);
        partial void OnCustomer_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Employee_ID
        {
            get
            {
                return _Employee_ID;
            }
            set
            {
                OnEmployee_IDChanging(value);
                ReportPropertyChanging("Employee_ID");
                _Employee_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Employee_ID");
                OnEmployee_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Employee_ID;
        partial void OnEmployee_IDChanging(Nullable<global::System.Int32> value);
        partial void OnEmployee_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Name
        {
            get
            {
                return _Ship_Name;
            }
            set
            {
                OnShip_NameChanging(value);
                ReportPropertyChanging("Ship_Name");
                _Ship_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Name");
                OnShip_NameChanged();
            }
        }
        private global::System.String _Ship_Name;
        partial void OnShip_NameChanging(global::System.String value);
        partial void OnShip_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Address
        {
            get
            {
                return _Ship_Address;
            }
            set
            {
                OnShip_AddressChanging(value);
                ReportPropertyChanging("Ship_Address");
                _Ship_Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Address");
                OnShip_AddressChanged();
            }
        }
        private global::System.String _Ship_Address;
        partial void OnShip_AddressChanging(global::System.String value);
        partial void OnShip_AddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_City
        {
            get
            {
                return _Ship_City;
            }
            set
            {
                OnShip_CityChanging(value);
                ReportPropertyChanging("Ship_City");
                _Ship_City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_City");
                OnShip_CityChanged();
            }
        }
        private global::System.String _Ship_City;
        partial void OnShip_CityChanging(global::System.String value);
        partial void OnShip_CityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Region
        {
            get
            {
                return _Ship_Region;
            }
            set
            {
                OnShip_RegionChanging(value);
                ReportPropertyChanging("Ship_Region");
                _Ship_Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Region");
                OnShip_RegionChanged();
            }
        }
        private global::System.String _Ship_Region;
        partial void OnShip_RegionChanging(global::System.String value);
        partial void OnShip_RegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Postal_Code
        {
            get
            {
                return _Ship_Postal_Code;
            }
            set
            {
                OnShip_Postal_CodeChanging(value);
                ReportPropertyChanging("Ship_Postal_Code");
                _Ship_Postal_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Postal_Code");
                OnShip_Postal_CodeChanged();
            }
        }
        private global::System.String _Ship_Postal_Code;
        partial void OnShip_Postal_CodeChanging(global::System.String value);
        partial void OnShip_Postal_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ship_Country
        {
            get
            {
                return _Ship_Country;
            }
            set
            {
                OnShip_CountryChanging(value);
                ReportPropertyChanging("Ship_Country");
                _Ship_Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ship_Country");
                OnShip_CountryChanged();
            }
        }
        private global::System.String _Ship_Country;
        partial void OnShip_CountryChanging(global::System.String value);
        partial void OnShip_CountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ship_Via
        {
            get
            {
                return _Ship_Via;
            }
            set
            {
                OnShip_ViaChanging(value);
                ReportPropertyChanging("Ship_Via");
                _Ship_Via = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ship_Via");
                OnShip_ViaChanged();
            }
        }
        private Nullable<global::System.Int32> _Ship_Via;
        partial void OnShip_ViaChanging(Nullable<global::System.Int32> value);
        partial void OnShip_ViaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Order_Date
        {
            get
            {
                return _Order_Date;
            }
            set
            {
                OnOrder_DateChanging(value);
                ReportPropertyChanging("Order_Date");
                _Order_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order_Date");
                OnOrder_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Order_Date;
        partial void OnOrder_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrder_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Required_Date
        {
            get
            {
                return _Required_Date;
            }
            set
            {
                OnRequired_DateChanging(value);
                ReportPropertyChanging("Required_Date");
                _Required_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Required_Date");
                OnRequired_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Required_Date;
        partial void OnRequired_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnRequired_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Shipped_Date
        {
            get
            {
                return _Shipped_Date;
            }
            set
            {
                OnShipped_DateChanging(value);
                ReportPropertyChanging("Shipped_Date");
                _Shipped_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shipped_Date");
                OnShipped_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Shipped_Date;
        partial void OnShipped_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnShipped_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Freight
        {
            get
            {
                return _Freight;
            }
            set
            {
                OnFreightChanging(value);
                ReportPropertyChanging("Freight");
                _Freight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Freight");
                OnFreightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Freight;
        partial void OnFreightChanging(Nullable<global::System.Decimal> value);
        partial void OnFreightChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK00", "Customers")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("NorthwindModel.Orders_FK00", "Customers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK02", "Employees")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("NorthwindModel.Orders_FK02", "Employees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Order_Details_FK01", "Order_Details")]
        public EntityCollection<Order_Detail> Order_Details
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order_Detail>("NorthwindModel.Order_Details_FK01", "Order_Details");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order_Detail>("NorthwindModel.Order_Details_FK01", "Order_Details", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK01", "Shippers")]
        public Shipper Shipper
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shipper>("NorthwindModel.Orders_FK01", "Shippers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shipper>("NorthwindModel.Orders_FK01", "Shippers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shipper> ShipperReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shipper>("NorthwindModel.Orders_FK01", "Shippers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shipper>("NorthwindModel.Orders_FK01", "Shippers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Order_Detail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order_Detail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order_Detail object.
        /// </summary>
        /// <param name="order_ID">Initial value of the Order_ID property.</param>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        /// <param name="unit_Price">Initial value of the Unit_Price property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="discount">Initial value of the Discount property.</param>
        public static Order_Detail CreateOrder_Detail(global::System.Int32 order_ID, global::System.Int32 product_ID, global::System.Decimal unit_Price, global::System.Int16 quantity, global::System.Single discount)
        {
            Order_Detail order_Detail = new Order_Detail();
            order_Detail.Order_ID = order_ID;
            order_Detail.Product_ID = product_ID;
            order_Detail.Unit_Price = unit_Price;
            order_Detail.Quantity = quantity;
            order_Detail.Discount = discount;
            return order_Detail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order_ID
        {
            get
            {
                return _Order_ID;
            }
            set
            {
                if (_Order_ID != value)
                {
                    OnOrder_IDChanging(value);
                    ReportPropertyChanging("Order_ID");
                    _Order_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Order_ID");
                    OnOrder_IDChanged();
                }
            }
        }
        private global::System.Int32 _Order_ID;
        partial void OnOrder_IDChanging(global::System.Int32 value);
        partial void OnOrder_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                if (_Product_ID != value)
                {
                    OnProduct_IDChanging(value);
                    ReportPropertyChanging("Product_ID");
                    _Product_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_ID");
                    OnProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_ID;
        partial void OnProduct_IDChanging(global::System.Int32 value);
        partial void OnProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Unit_Price
        {
            get
            {
                return _Unit_Price;
            }
            set
            {
                OnUnit_PriceChanging(value);
                ReportPropertyChanging("Unit_Price");
                _Unit_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Unit_Price");
                OnUnit_PriceChanged();
            }
        }
        private global::System.Decimal _Unit_Price;
        partial void OnUnit_PriceChanging(global::System.Decimal value);
        partial void OnUnit_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int16 _Quantity;
        partial void OnQuantityChanging(global::System.Int16 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                OnDiscountChanging(value);
                ReportPropertyChanging("Discount");
                _Discount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discount");
                OnDiscountChanged();
            }
        }
        private global::System.Single _Discount;
        partial void OnDiscountChanging(global::System.Single value);
        partial void OnDiscountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Order_Details_FK00", "Products")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("NorthwindModel.Order_Details_FK00", "Products").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("NorthwindModel.Order_Details_FK00", "Products").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("NorthwindModel.Order_Details_FK00", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("NorthwindModel.Order_Details_FK00", "Products", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Order_Details_FK01", "Orders")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("NorthwindModel.Order_Details_FK01", "Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("NorthwindModel.Order_Details_FK01", "Orders").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("NorthwindModel.Order_Details_FK01", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("NorthwindModel.Order_Details_FK01", "Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        /// <param name="product_Name">Initial value of the Product_Name property.</param>
        /// <param name="discontinued">Initial value of the Discontinued property.</param>
        public static Product CreateProduct(global::System.Int32 product_ID, global::System.String product_Name, global::System.Boolean discontinued)
        {
            Product product = new Product();
            product.Product_ID = product_ID;
            product.Product_Name = product_Name;
            product.Discontinued = discontinued;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                if (_Product_ID != value)
                {
                    OnProduct_IDChanging(value);
                    ReportPropertyChanging("Product_ID");
                    _Product_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_ID");
                    OnProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_ID;
        partial void OnProduct_IDChanging(global::System.Int32 value);
        partial void OnProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Supplier_ID
        {
            get
            {
                return _Supplier_ID;
            }
            set
            {
                OnSupplier_IDChanging(value);
                ReportPropertyChanging("Supplier_ID");
                _Supplier_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Supplier_ID");
                OnSupplier_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Supplier_ID;
        partial void OnSupplier_IDChanging(Nullable<global::System.Int32> value);
        partial void OnSupplier_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Category_ID
        {
            get
            {
                return _Category_ID;
            }
            set
            {
                OnCategory_IDChanging(value);
                ReportPropertyChanging("Category_ID");
                _Category_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Category_ID");
                OnCategory_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Category_ID;
        partial void OnCategory_IDChanging(Nullable<global::System.Int32> value);
        partial void OnCategory_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String English_Name
        {
            get
            {
                return _English_Name;
            }
            set
            {
                OnEnglish_NameChanging(value);
                ReportPropertyChanging("English_Name");
                _English_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("English_Name");
                OnEnglish_NameChanged();
            }
        }
        private global::System.String _English_Name;
        partial void OnEnglish_NameChanging(global::System.String value);
        partial void OnEnglish_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Quantity_Per_Unit
        {
            get
            {
                return _Quantity_Per_Unit;
            }
            set
            {
                OnQuantity_Per_UnitChanging(value);
                ReportPropertyChanging("Quantity_Per_Unit");
                _Quantity_Per_Unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Quantity_Per_Unit");
                OnQuantity_Per_UnitChanged();
            }
        }
        private global::System.String _Quantity_Per_Unit;
        partial void OnQuantity_Per_UnitChanging(global::System.String value);
        partial void OnQuantity_Per_UnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Unit_Price
        {
            get
            {
                return _Unit_Price;
            }
            set
            {
                OnUnit_PriceChanging(value);
                ReportPropertyChanging("Unit_Price");
                _Unit_Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Unit_Price");
                OnUnit_PriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Unit_Price;
        partial void OnUnit_PriceChanging(Nullable<global::System.Decimal> value);
        partial void OnUnit_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Units_In_Stock
        {
            get
            {
                return _Units_In_Stock;
            }
            set
            {
                OnUnits_In_StockChanging(value);
                ReportPropertyChanging("Units_In_Stock");
                _Units_In_Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Units_In_Stock");
                OnUnits_In_StockChanged();
            }
        }
        private Nullable<global::System.Int16> _Units_In_Stock;
        partial void OnUnits_In_StockChanging(Nullable<global::System.Int16> value);
        partial void OnUnits_In_StockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Units_On_Order
        {
            get
            {
                return _Units_On_Order;
            }
            set
            {
                OnUnits_On_OrderChanging(value);
                ReportPropertyChanging("Units_On_Order");
                _Units_On_Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Units_On_Order");
                OnUnits_On_OrderChanged();
            }
        }
        private Nullable<global::System.Int16> _Units_On_Order;
        partial void OnUnits_On_OrderChanging(Nullable<global::System.Int16> value);
        partial void OnUnits_On_OrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Reorder_Level
        {
            get
            {
                return _Reorder_Level;
            }
            set
            {
                OnReorder_LevelChanging(value);
                ReportPropertyChanging("Reorder_Level");
                _Reorder_Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reorder_Level");
                OnReorder_LevelChanged();
            }
        }
        private Nullable<global::System.Int16> _Reorder_Level;
        partial void OnReorder_LevelChanging(Nullable<global::System.Int16> value);
        partial void OnReorder_LevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                OnDiscontinuedChanging(value);
                ReportPropertyChanging("Discontinued");
                _Discontinued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Discontinued");
                OnDiscontinuedChanged();
            }
        }
        private global::System.Boolean _Discontinued;
        partial void OnDiscontinuedChanging(global::System.Boolean value);
        partial void OnDiscontinuedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK01", "Categories")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("NorthwindModel.Products_FK01", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Order_Details_FK00", "Order_Details")]
        public EntityCollection<Order_Detail> Order_Details
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order_Detail>("NorthwindModel.Order_Details_FK00", "Order_Details");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order_Detail>("NorthwindModel.Order_Details_FK00", "Order_Details", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK00", "Suppliers")]
        public Supplier Supplier
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Supplier>("NorthwindModel.Products_FK00", "Suppliers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Supplier>("NorthwindModel.Products_FK00", "Suppliers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Supplier> SupplierReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Supplier>("NorthwindModel.Products_FK00", "Suppliers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Supplier>("NorthwindModel.Products_FK00", "Suppliers", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Shipper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shipper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shipper object.
        /// </summary>
        /// <param name="shipper_ID">Initial value of the Shipper_ID property.</param>
        /// <param name="company_Name">Initial value of the Company_Name property.</param>
        public static Shipper CreateShipper(global::System.Int32 shipper_ID, global::System.String company_Name)
        {
            Shipper shipper = new Shipper();
            shipper.Shipper_ID = shipper_ID;
            shipper.Company_Name = company_Name;
            return shipper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Shipper_ID
        {
            get
            {
                return _Shipper_ID;
            }
            set
            {
                if (_Shipper_ID != value)
                {
                    OnShipper_IDChanging(value);
                    ReportPropertyChanging("Shipper_ID");
                    _Shipper_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Shipper_ID");
                    OnShipper_IDChanged();
                }
            }
        }
        private global::System.Int32 _Shipper_ID;
        partial void OnShipper_IDChanging(global::System.Int32 value);
        partial void OnShipper_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company_Name
        {
            get
            {
                return _Company_Name;
            }
            set
            {
                OnCompany_NameChanging(value);
                ReportPropertyChanging("Company_Name");
                _Company_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company_Name");
                OnCompany_NameChanged();
            }
        }
        private global::System.String _Company_Name;
        partial void OnCompany_NameChanging(global::System.String value);
        partial void OnCompany_NameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Orders_FK01", "Orders")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("NorthwindModel.Orders_FK01", "Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("NorthwindModel.Orders_FK01", "Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NorthwindModel", Name="Supplier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Supplier : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Supplier object.
        /// </summary>
        /// <param name="supplier_ID">Initial value of the Supplier_ID property.</param>
        /// <param name="company_Name">Initial value of the Company_Name property.</param>
        public static Supplier CreateSupplier(global::System.Int32 supplier_ID, global::System.String company_Name)
        {
            Supplier supplier = new Supplier();
            supplier.Supplier_ID = supplier_ID;
            supplier.Company_Name = company_Name;
            return supplier;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Supplier_ID
        {
            get
            {
                return _Supplier_ID;
            }
            set
            {
                if (_Supplier_ID != value)
                {
                    OnSupplier_IDChanging(value);
                    ReportPropertyChanging("Supplier_ID");
                    _Supplier_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Supplier_ID");
                    OnSupplier_IDChanged();
                }
            }
        }
        private global::System.Int32 _Supplier_ID;
        partial void OnSupplier_IDChanging(global::System.Int32 value);
        partial void OnSupplier_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Company_Name
        {
            get
            {
                return _Company_Name;
            }
            set
            {
                OnCompany_NameChanging(value);
                ReportPropertyChanging("Company_Name");
                _Company_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Company_Name");
                OnCompany_NameChanged();
            }
        }
        private global::System.String _Company_Name;
        partial void OnCompany_NameChanging(global::System.String value);
        partial void OnCompany_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact_Name
        {
            get
            {
                return _Contact_Name;
            }
            set
            {
                OnContact_NameChanging(value);
                ReportPropertyChanging("Contact_Name");
                _Contact_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact_Name");
                OnContact_NameChanged();
            }
        }
        private global::System.String _Contact_Name;
        partial void OnContact_NameChanging(global::System.String value);
        partial void OnContact_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact_Title
        {
            get
            {
                return _Contact_Title;
            }
            set
            {
                OnContact_TitleChanging(value);
                ReportPropertyChanging("Contact_Title");
                _Contact_Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contact_Title");
                OnContact_TitleChanged();
            }
        }
        private global::System.String _Contact_Title;
        partial void OnContact_TitleChanging(global::System.String value);
        partial void OnContact_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postal_Code
        {
            get
            {
                return _Postal_Code;
            }
            set
            {
                OnPostal_CodeChanging(value);
                ReportPropertyChanging("Postal_Code");
                _Postal_Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Postal_Code");
                OnPostal_CodeChanged();
            }
        }
        private global::System.String _Postal_Code;
        partial void OnPostal_CodeChanging(global::System.String value);
        partial void OnPostal_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "Products_FK00", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("NorthwindModel.Products_FK00", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("NorthwindModel.Products_FK00", "Products", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
